<?php

namespace AppBundle\Repository;

/**
 * MarquageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarquageRepository extends \Doctrine\ORM\EntityRepository
{
}
